version: "3.9"

services:
  postgres:
    image: postgres:12-bullseye
    restart: always
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3

  backend:
    build:
      context: backend
    ports:
      - "{{ cookiecutter.backend_port }}:{{ cookiecutter.backend_port }}"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  app-db-data:
  root-home:
